<a href="https://colab.research.google.com/github/Mikhthad/Bike_sharing/blob/main/Bike_sharing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/bike_sharing.csv')

In [3]:
df

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0000,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0000,8,32,40
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0000,5,27,32
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0000,3,10,13
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
10881,2012-12-19 19:00:00,4,0,1,1,15.58,19.695,50,26.0027,7,329,336
10882,2012-12-19 20:00:00,4,0,1,1,14.76,17.425,57,15.0013,10,231,241
10883,2012-12-19 21:00:00,4,0,1,1,13.94,15.910,61,15.0013,4,164,168
10884,2012-12-19 22:00:00,4,0,1,1,13.94,17.425,61,6.0032,12,117,129
10885,2012-12-19 23:00:00,4,0,1,1,13.12,16.665,66,8.9981,4,84,88

In [ ]:
df.head(10)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0000,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0000,8,32,40
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0000,5,27,32
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0000,3,10,13
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0000,0,1,1
5,2011-01-01 05:00:00,1,0,0,2,9.84,12.880,75,6.0032,0,1,1
6,2011-01-01 06:00:00,1,0,0,1,9.02,13.635,80,0.0000,2,0,2
7,2011-01-01 07:00:00,1,0,0,1,8.20,12.880,86,0.0000,1,2,3
8,2011-01-01 08:00:00,1,0,0,1,9.84,14.395,75,0.0000,1,7,8
9,2011-01-01 09:00:00,1,0,0,1,13.12,17.425,76,0.0000,8,6,14

In [ ]:
df.tail(5)

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
10881,2012-12-19 19:00:00,4,0,1,1,15.58,19.695,50,26.0027,7,329,336
10882,2012-12-19 20:00:00,4,0,1,1,14.76,17.425,57,15.0013,10,231,241
10883,2012-12-19 21:00:00,4,0,1,1,13.94,15.910,61,15.0013,4,164,168
10884,2012-12-19 22:00:00,4,0,1,1,13.94,17.425,61,6.0032,12,117,129
10885,2012-12-19 23:00:00,4,0,1,1,13.12,16.665,66,8.9981,4,84,88

In [4]:
df.shape

(10886, 12)

In [5]:
df.size

130632

In [7]:
df.dtypes

datetime       object
season          int64
holiday         int64
workingday      int64
weather         int64
temp          float64
atemp         float64
humidity        int64
windspeed     float64
casual          int64
registered      int64
count           int64
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   datetime    10886 non-null  object
 1   season      10886 non-null  int64
 2   holiday     10886 non-null  int64
 3   workingday  10886 non-null  int64
 4   weather     10886 non-null  int64
 5   temp        10886 non-null  float64
 6   atemp       10886 non-null  float64
 7   humidity    10886 non-null  int64
 8   windspeed   10886 non-null  float64
 9   casual      10886 non-null  int64
 10  registered  10886 non-null  int64
 11  count       10886 non-null  int64
dtypes: float64(3), int64(8), object(1)
memory usage: 1020.7+ KB

In [ ]:
# 1) get details windspeed greater than 25
df[df['windspeed']>=25]

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
42,2011-01-02 19:00:00,1,0,0,1,13.12,14.395,42,30.0026,1,29,30
48,2011-01-03 01:00:00,1,0,1,1,8.20,8.335,44,27.9993,0,2,2
49,2011-01-03 04:00:00,1,0,1,1,6.56,6.820,47,26.0027,0,1,1
51,2011-01-03 06:00:00,1,0,1,1,5.74,5.305,50,26.0027,0,30,30
54,2011-01-03 09:00:00,1,0,1,1,6.56,6.820,43,26.0027,7,81,88
...,...,...,...,...,...,...,...,...,...,...,...,...
10854,2012-12-18 16:00:00,4,0,1,1,18.04,21.970,41,31.0009,40,323,363
10855,2012-12-18 17:00:00,4,0,1,1,16.40,20.455,47,30.0026,39,533,572
10857,2012-12-18 19:00:00,4,0,1,1,15.58,19.695,46,26.0027,19,334,353
10879,2012-12-19 17:00:00,4,0,1,1,16.40,20.455,50,26.0027,26,536,562
10881,2012-12-19 19:00:00,4,0,1,1,15.58,19.695,50,26.0027,7,329,336

In [ ]:
# 2) get details register greater than 300
df[df['registered']>300]

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
1403,2011-04-04 08:00:00,2,0,1,2,18.86,22.725,55,19.9995,31,308,339
1413,2011-04-04 18:00:00,2,0,1,2,29.52,31.820,23,32.9975,78,308,386
1451,2011-04-06 08:00:00,2,0,1,1,13.12,15.150,61,15.0013,17,308,325
1460,2011-04-06 17:00:00,2,0,1,1,21.32,25.000,32,30.0026,53,303,356
1579,2011-04-11 17:00:00,2,0,1,1,30.34,33.335,48,35.0008,100,352,452
...,...,...,...,...,...,...,...,...,...,...,...,...
10870,2012-12-19 08:00:00,4,0,1,1,9.84,12.880,87,7.0015,13,665,678
10871,2012-12-19 09:00:00,4,0,1,1,11.48,14.395,75,7.0015,8,309,317
10879,2012-12-19 17:00:00,4,0,1,1,16.40,20.455,50,26.0027,26,536,562
10880,2012-12-19 18:00:00,4,0,1,1,15.58,19.695,50,23.9994,23,546,569
10881,2012-12-19 19:00:00,4,0,1,1,15.58,19.695,50,26.0027,7,329,336

In [ ]:
# 3) get details temprature lower 10
df[df['temp']<=10]

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0000,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0000,8,32,40
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0000,5,27,32
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0000,3,10,13
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
10772,2012-12-15 06:00:00,4,0,0,2,9.84,14.395,75,0.0000,0,11,11
10773,2012-12-15 07:00:00,4,0,0,2,9.84,12.880,75,6.0032,1,47,48
10866,2012-12-19 04:00:00,4,0,1,1,9.84,12.120,75,8.9981,1,6,7
10868,2012-12-19 06:00:00,4,0,1,1,9.84,12.880,75,6.0032,3,109,112
10870,2012-12-19 08:00:00,4,0,1,1,9.84,12.880,87,7.0015,13,665,678

In [ ]:
# 4) get details humidity greater than 80 and registered greater than 600
df[(df['humidity']>=80) & (df['registered']>=600)]

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
6649,2012-03-14 08:00:00,1,0,1,1,18.04,21.970,82,0.0000,34,628,662
7223,2012-04-19 08:00:00,2,0,1,2,17.22,21.210,82,7.0015,26,651,677
7271,2012-05-02 08:00:00,2,0,1,2,22.96,26.515,88,0.0000,26,640,666
7295,2012-05-03 08:00:00,2,0,1,3,18.86,22.725,88,12.9980,19,608,627
7391,2012-05-07 08:00:00,2,0,1,2,20.50,24.240,82,12.9980,31,608,639
7607,2012-05-16 08:00:00,2,0,1,1,23.78,27.275,83,0.0000,33,617,650
7703,2012-06-01 08:00:00,2,0,1,2,26.24,28.790,89,12.9980,19,675,694
7976,2012-06-12 17:00:00,2,0,1,2,27.06,29.545,89,19.0012,56,625,681
9143,2012-09-04 08:00:00,3,0,1,1,28.70,33.335,84,11.0014,15,617,632
9215,2012-09-07 08:00:00,3,0,1,1,27.06,30.305,83,7.0015,29,690,719
9479,2012-09-18 08:00:00,3,0,1,2,27.06,30.305,83,36.9974,32,640,672
9560,2012-10-02 17:00:00,4,0,1,3,25.42,28.030,88,7.0015,38,677,715
9561,2012-10-02 18:00:00,4,0,1,3,25.42,27.275,94,6.0032,48,639,687
9575,2012-10-03 08:00:00,4,0,1,2,25.42,28.030,88,7.0015,28,781,809
9599,2012-10-04 08:00:00,4,0,1,1,26.24,28.790,89,0.0000,27,711,738
9719,2012-10-09 08:00:00,4,0,1,2,17.22,21.210,80,12.9980,15,698,713
9935,2012-10-18 08:00:00,4,0,1,1,18.86,22.725,82,16.9979,31,803,834
10486,2012-12-03 08:00:00,4,0,1,1,14.76,18.940,93,0.0000,19,712,731
10510,2012-12-04 08:00:00,4,0,1,2,18.04,21.970,88,11.0014,21,700,721
10846,2012-12-18 08:00:00,4,0,1,1,15.58,19.695,94,0.0000,10,652,662
10870,2012-12-19 08:00:00,4,0,1,1,9.84,12.880,87,7.0015,13,665,678

In [ ]:
df

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0000,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0000,8,32,40
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0000,5,27,32
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0000,3,10,13
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
10881,2012-12-19 19:00:00,4,0,1,1,15.58,19.695,50,26.0027,7,329,336
10882,2012-12-19 20:00:00,4,0,1,1,14.76,17.425,57,15.0013,10,231,241
10883,2012-12-19 21:00:00,4,0,1,1,13.94,15.910,61,15.0013,4,164,168
10884,2012-12-19 22:00:00,4,0,1,1,13.94,17.425,61,6.0032,12,117,129
10885,2012-12-19 23:00:00,4,0,1,1,13.12,16.665,66,8.9981,4,84,88

In [ ]:
# 5) to print holiday
df.loc[df['holiday']==1,'holiday']

372      1
373      1
374      1
375      1
376      1
        ..
10257    1
10258    1
10259    1
10260    1
10261    1
Name: holiday, Length: 311, dtype: int64

In [ ]:
# 6) get details winter
df[df['season']==4]

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
4055,2011-10-01 00:00:00,4,0,0,1,20.50,24.240,63,26.0027,24,106,130
4056,2011-10-01 01:00:00,4,0,0,1,19.68,23.485,67,22.0028,11,47,58
4057,2011-10-01 02:00:00,4,0,0,1,18.86,22.725,63,27.9993,21,46,67
4058,2011-10-01 03:00:00,4,0,0,1,18.86,22.725,59,27.9993,8,17,25
4059,2011-10-01 04:00:00,4,0,0,1,18.04,21.970,58,27.9993,2,6,8
...,...,...,...,...,...,...,...,...,...,...,...,...
10881,2012-12-19 19:00:00,4,0,1,1,15.58,19.695,50,26.0027,7,329,336
10882,2012-12-19 20:00:00,4,0,1,1,14.76,17.425,57,15.0013,10,231,241
10883,2012-12-19 21:00:00,4,0,1,1,13.94,15.910,61,15.0013,4,164,168
10884,2012-12-19 22:00:00,4,0,1,1,13.94,17.425,61,6.0032,12,117,129
10885,2012-12-19 23:00:00,4,0,1,1,13.12,16.665,66,8.9981,4,84,88

In [ ]:
# 7) get details summer and temp greater than 30
df[(df['season']==2) & (df['temp']>=30)]

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
1409,2011-04-04 14:00:00,2,0,1,2,30.34,32.575,27,32.9975,47,76,123
1410,2011-04-04 15:00:00,2,0,1,1,31.16,33.335,23,36.9974,47,96,143
1411,2011-04-04 16:00:00,2,0,1,1,31.16,32.575,22,35.0008,59,130,189
1412,2011-04-04 17:00:00,2,0,1,1,30.34,32.575,23,40.9973,83,283,366
1577,2011-04-11 15:00:00,2,0,1,1,30.34,33.335,48,35.0008,56,85,141
...,...,...,...,...,...,...,...,...,...,...,...,...
8144,2012-06-19 17:00:00,2,0,1,1,32.80,37.880,55,12.9980,86,725,811
8145,2012-06-19 18:00:00,2,0,1,1,32.80,37.880,55,11.0014,91,704,795
8146,2012-06-19 19:00:00,2,0,1,1,32.80,38.635,59,15.0013,82,432,514
8147,2012-06-19 20:00:00,2,0,1,1,32.80,37.880,55,16.9979,59,399,458
8148,2012-06-19 21:00:00,2,0,1,1,31.16,35.605,62,11.0014,37,239,276

In [ ]:
# 8) get details casual greter than 100 or registerd lower than 100
df[(df['casual']>=100) | (df['registered']<=100)]

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0000,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0000,8,32,40
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0000,5,27,32
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0000,3,10,13
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
10864,2012-12-19 02:00:00,4,0,1,1,11.48,15.150,65,6.0032,1,2,3
10865,2012-12-19 03:00:00,4,0,1,1,10.66,13.635,75,8.9981,0,5,5
10866,2012-12-19 04:00:00,4,0,1,1,9.84,12.120,75,8.9981,1,6,7
10867,2012-12-19 05:00:00,4,0,1,1,10.66,14.395,75,6.0032,2,29,31
10885,2012-12-19 23:00:00,4,0,1,1,13.12,16.665,66,8.9981,4,84,88

In [ ]:
# 9) get details atemp grater than 20
df[df['atemp']>=30]

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
819,2011-02-17 14:00:00,1,0,1,1,24.60,31.060,31,15.0013,26,55,81
820,2011-02-17 15:00:00,1,0,1,1,24.60,30.305,28,16.9979,15,91,106
842,2011-02-18 13:00:00,1,0,1,1,24.60,31.060,43,12.9980,45,131,176
843,2011-02-18 14:00:00,1,0,1,1,27.06,31.060,36,19.9995,73,118,191
844,2011-02-18 15:00:00,1,0,1,1,27.06,31.060,36,22.0028,55,117,172
...,...,...,...,...,...,...,...,...,...,...,...,...
10251,2012-11-12 13:00:00,4,1,0,1,24.60,30.305,60,15.0013,108,312,420
10492,2012-12-03 14:00:00,4,0,1,1,24.60,31.060,53,0.0000,51,209,260
10493,2012-12-03 15:00:00,4,0,1,1,24.60,31.060,56,0.0000,58,210,268
10494,2012-12-03 16:00:00,4,0,1,1,24.60,31.060,53,8.9981,45,397,442
10517,2012-12-04 15:00:00,4,0,1,2,24.60,31.060,49,16.9979,56,244,300

In [ ]:
#10) to print weather
df.loc[:,'weather']

0        1
1        1
2        1
3        1
4        1
        ..
10881    1
10882    1
10883    1
10884    1
10885    1
Name: weather, Length: 10886, dtype: int64